// export const phimbo = "Phim Bộ"
// export const phimmoi = "Phim Mới"
// export const phimTm = "Phim Thuyết Minh"
// export const phimCr = "Phim Chiếu Rạp"
// export const Tvshow = "Tv Show"
// export const  = "Phim Mới"
// export const phimmoi = "Phim Mới"
// export const phimmoi = "Phim Mới"
// export const phimmoi = "Phim Mới"

// export const phimmoi = "Phim Mới"
// export const phimmoi = "Phim Mới"
// export const phimmoi = "Phim Mới"
// export const phimmoi = "Phim Mới"
// export const phimmoi = "Phim Mới"
// export const phimmoi = "Phim Mới"
